# Generated by Django 4.2.7 on 2023-11-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("memory_type", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("producer", models.CharField(max_length=100)),
                ("clock", models.PositiveIntegerField()),
                ("timings", models.CharField(max_length=20)),
                ("sticks", models.PositiveIntegerField()),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True, max_length=20)),
            ],
            options={
                "db_table": "ram",
            },
        ),
    ]
