# Generated by Django 4.2.7 on 2023-11-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_gpu_alter_motherboard_display_port_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpu",
            name="slots",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterModelTable(
            name="gpu",
            table="gpu",
        ),
    ]
