# Generated by Django 4.2.7 on 2023-11-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_gpu_slots_alter_gpu_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gpu",
            table=None,
        ),
    ]
