# Generated by Django 4.2.7 on 2023-11-26 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_alter_pc_cpu"),
    ]

    operations = [
        migrations.CreateModel(
            name="PCMotherboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "motherboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PCs",
                        to="dashboard.motherboard",
                    ),
                ),
            ],
            options={
                "db_table": "pc_motherboard",
            },
        ),
        migrations.CreateModel(
            name="PCParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "cpu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PCs",
                        to="dashboard.cpu",
                    ),
                ),
                (
                    "gpu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PCs",
                        to="dashboard.gpu",
                    ),
                ),
                (
                    "ram",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PCs",
                        to="dashboard.ram",
                    ),
                ),
            ],
            options={
                "db_table": "pc_parts",
            },
        ),
        migrations.DeleteModel(
            name="PC",
        ),
    ]
