# Generated by Django 4.2.7 on 2023-11-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_pcmotherboard_pcparts_delete_pc"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcparts",
            name="pc_motherboard",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.pcmotherboard",
            ),
        ),
        migrations.AlterField(
            model_name="pcmotherboard",
            name="motherboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.motherboard"
            ),
        ),
        migrations.AlterField(
            model_name="pcparts",
            name="cpu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.cpu",
            ),
        ),
        migrations.AlterField(
            model_name="pcparts",
            name="gpu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.gpu",
            ),
        ),
        migrations.AlterField(
            model_name="pcparts",
            name="ram",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.ram",
            ),
        ),
    ]
