# Generated by Django 4.2.7 on 2023-11-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_pcparts_pc_motherboard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcparts",
            name="pc_motherboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.pcmotherboard",
            ),
        ),
    ]
