# Generated by Django 4.2.7 on 2023-11-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_pcparts_pc_motherboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcmotherboard",
            name="motherboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pc_motherboard",
                to="dashboard.motherboard",
            ),
        ),
        migrations.DeleteModel(
            name="PCParts",
        ),
    ]
