# Generated by Django 4.2.7 on 2023-11-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_pcparts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Field",
        ),
    ]
