# Generated by Django 4.2.7 on 2023-11-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pcparts",
            name="cpu",
        ),
        migrations.RemoveField(
            model_name="pcparts",
            name="gpu",
        ),
        migrations.RemoveField(
            model_name="pcparts",
            name="pc_motherboard",
        ),
        migrations.RemoveField(
            model_name="pcparts",
            name="ram",
        ),
        migrations.DeleteModel(
            name="PCMotherboard",
        ),
        migrations.DeleteModel(
            name="PCParts",
        ),
    ]
