# Generated by Django 4.2.7 on 2023-11-27 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_cpu_field_gpu_field_ram_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPUField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "cpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.cpu"
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.field",
                    ),
                ),
            ],
        ),
    ]
