# Generated by Django 4.2.7 on 2023-11-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_cpufield"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cpufield",
            table="cpu_field",
        ),
    ]
