# Generated by Django 4.2.7 on 2023-11-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_alter_cpufield_field_ramfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPUField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.field",
                    ),
                ),
                (
                    "gpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.gpu"
                    ),
                ),
            ],
            options={
                "db_table": "gpu_field",
            },
        ),
    ]
