# Generated by Django 4.2.7 on 2023-12-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_gpufield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpu",
            name="field",
        ),
        migrations.RemoveField(
            model_name="gpu",
            name="field",
        ),
        migrations.RemoveField(
            model_name="ram",
            name="field",
        ),
        migrations.DeleteModel(
            name="GPUField",
        ),
    ]
