# Generated by Django 4.2.7 on 2023-12-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0028_remove_cpu_field_remove_gpu_field_remove_ram_field_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GPUField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.field",
                    ),
                ),
                (
                    "gpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.gpu"
                    ),
                ),
            ],
            options={
                "db_table": "gpu_field",
            },
        ),
    ]
