# Generated by Django 4.2.7 on 2023-12-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_gpufield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ramfield",
            name="field",
        ),
        migrations.RemoveField(
            model_name="ramfield",
            name="ram",
        ),
        migrations.DeleteModel(
            name="Ram",
        ),
        migrations.DeleteModel(
            name="RAMField",
        ),
    ]
