# Generated by Django 4.2.7 on 2023-12-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_ram_ramfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="ram",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
