# Generated by Django 4.2.7 on 2023-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_cpu_image_url_gpu_image_url_motherboard_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="cpu_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name="field",
            name="gpu_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name="field",
            name="motherboard_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name="field",
            name="ram_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
