# Generated by Django 4.2.7 on 2023-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_field_cpu_budget_field_gpu_budget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="having_gpu",
            field=models.BooleanField(default=True),
        ),
    ]
