# Generated by Django 4.2.7 on 2023-12-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0036_ramtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ramtype",
            name="type",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
