# Generated by Django 4.2.7 on 2023-12-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_ramtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="motherboard",
            name="ram_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.ramtype",
            ),
        ),
    ]
