# Generated by Django 4.2.7 on 2023-12-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0040_motherboard_ram_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motherboard",
            name="memory_type",
        ),
    ]
