# Generated by Django 4.2.7 on 2023-12-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0043_remove_ram_memory_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ramfield",
            name="field",
        ),
        migrations.RemoveField(
            model_name="ramfield",
            name="ram",
        ),
        migrations.AlterField(
            model_name="cpu",
            name="producer",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="producer",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="producer",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="RAM",
        ),
        migrations.DeleteModel(
            name="RAMField",
        ),
    ]
