# Generated by Django 4.2.7 on 2023-12-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0046_ram_producer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ram",
            name="producer_id",
        ),
    ]
