# Generated by Django 4.2.7 on 2023-12-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0048_motherboard_producer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ram",
            name="producer_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.producer",
            ),
        ),
    ]
