# Generated by Django 4.2.7 on 2023-12-10 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0050_remove_motherboard_producer_remove_ram_producer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="motherboard",
            old_name="producer_id",
            new_name="producer",
        ),
        migrations.RenameField(
            model_name="ram",
            old_name="producer_id",
            new_name="producer",
        ),
        migrations.AddField(
            model_name="cpu",
            name="producer_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.producer",
            ),
        ),
    ]
