# Generated by Django 4.2.7 on 2023-12-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0051_rename_producer_id_motherboard_producer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpu",
            name="producer",
        ),
        migrations.AddField(
            model_name="gpu",
            name="producer_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.producer",
            ),
        ),
    ]
