# Generated by Django 4.2.7 on 2023-12-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0052_remove_cpu_producer_gpu_producer_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cpu",
            old_name="producer_id",
            new_name="producer",
        ),
        migrations.RemoveField(
            model_name="gpu",
            name="producer",
        ),
    ]
