# Generated by Django 4.2.7 on 2023-12-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0053_rename_producer_id_cpu_producer_remove_gpu_producer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gpu",
            old_name="producer_id",
            new_name="producer",
        ),
    ]
