# Generated by Django 4.2.7 on 2023-12-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0056_remove_case_type_case_case_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="case_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="casetype",
            old_name="name",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="ram",
            old_name="ram_type",
            new_name="type",
        ),
    ]
