# Generated by Django 4.2.7 on 2023-12-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0058_color"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Color",
        ),
    ]
