# Generated by Django 4.2.7 on 2023-12-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0059_delete_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "color",
            },
        ),
        migrations.AlterField(
            model_name="case",
            name="side_panel",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="casetype",
            name="type",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
