# Generated by Django 4.2.7 on 2023-12-11 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0063_alter_case_side_panel"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="case",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="case",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
