# Generated by Django 4.2.7 on 2023-12-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0066_alter_case_created_at_alter_case_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "drive_type",
            },
        ),
        migrations.CreateModel(
            name="InternalDrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capacity", models.PositiveIntegerField()),
                ("price_per_gb", models.DecimalField(decimal_places=2, max_digits=6)),
                ("cache", models.PositiveIntegerField()),
                ("form_factor", models.CharField(max_length=50)),
                ("interface", models.CharField(max_length=50)),
                ("image_url", models.URLField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "drive_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.drivetype",
                    ),
                ),
            ],
            options={
                "db_table": "internal_drive",
            },
        ),
    ]
