# Generated by Django 4.2.7 on 2023-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0067_drivetype_internaldrive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivetype",
            name="type",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
