# Generated by Django 4.2.7 on 2023-12-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0069_powersupplyefficiency_powersupplytype_powersupply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="powersupply",
            old_name="power_type",
            new_name="type",
        ),
    ]
