# Generated by Django 4.2.7 on 2023-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0070_rename_power_type_powersupply_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="case_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name="field",
            name="internal_drive_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name="field",
            name="power_supply_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
