# Generated by Django 4.2.7 on 2023-12-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0072_cpusocket_cpu_cpu_socket_motherboard_cpu_socket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpu",
            name="socket",
        ),
        migrations.RemoveField(
            model_name="motherboard",
            name="socket",
        ),
    ]
