# Generated by Django 4.2.7 on 2023-12-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0073_remove_cpu_socket_remove_motherboard_socket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cpu",
            old_name="cpu_socket",
            new_name="socket",
        ),
        migrations.RenameField(
            model_name="motherboard",
            old_name="cpu_socket",
            new_name="socket",
        ),
    ]
