# Generated by Django 4.2.7 on 2023-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0076_chipset_motherboard_chipset_f"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chipset",
            name="chipset",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
