# Generated by Django 4.2.7 on 2023-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0077_alter_chipset_chipset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motherboard",
            name="chipset",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
