# Generated by Django 4.2.7 on 2023-12-17 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0078_alter_motherboard_chipset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motherboard",
            name="chipset_f",
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="chipset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.chipset",
            ),
        ),
    ]
