# Generated by Django 4.2.7 on 2023-12-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0081_alter_case_created_at_alter_case_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpusocket",
            name="staus",
        ),
    ]
