# Generated by Django 4.2.7 on 2023-12-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0082_remove_cpusocket_staus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("factor", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "factor",
            },
        ),
        migrations.AddField(
            model_name="motherboard",
            name="factor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.factor",
            ),
        ),
    ]
