# Generated by Django 4.2.7 on 2023-12-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0087_remove_gpu_series"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gpu",
            old_name="gpu_series",
            new_name="series",
        ),
    ]
