# Generated by Django 4.2.7 on 2023-12-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0089_gpusync_gpu_gpu_sync"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gpu",
            name="sync",
        ),
    ]
