# Generated by Django 4.2.7 on 2023-12-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0090_remove_gpu_sync"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gpu",
            old_name="gpu_sync",
            new_name="sync",
        ),
    ]
