# Generated by Django 4.2.7 on 2023-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0092_rename_factor_formfactor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motherboard",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
