# Generated by Django 4.2.7 on 2023-12-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0093_alter_motherboard_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpu",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
