# Generated by Django 4.2.7 on 2023-12-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0094_alter_cpu_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ram",
            name="timings",
        ),
    ]
