# Generated by Django 4.2.7 on 2023-12-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0095_remove_ram_timings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ram",
            name="timings",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
