# Generated by Django 4.2.7 on 2023-12-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0097_gpu_cores"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="highest_performance",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
