# Generated by Django 4.2.7 on 2023-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0098_field_highest_performance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="highest_performance",
            field=models.PositiveIntegerField(),
        ),
    ]
