# Generated by Django 4.2.7 on 2023-12-26 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0100_casestyle"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="style",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.casestyle",
            ),
        ),
    ]
