# Generated by Django 4.2.7 on 2023-12-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0101_case_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="case_style",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.casestyle",
            ),
        ),
    ]
