# Generated by Django 4.2.7 on 2023-12-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0102_field_case_style"),
    ]

    operations = [
        migrations.RenameField(
            model_name="motherboard",
            old_name="image_url",
            new_name="external_image",
        ),
        migrations.AddField(
            model_name="motherboard",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
