# Generated by Django 4.2.7 on 2023-12-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0103_rename_image_url_motherboard_external_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="image_url",
            new_name="external_image",
        ),
        migrations.RenameField(
            model_name="cpu",
            old_name="image_url",
            new_name="external_image",
        ),
        migrations.RenameField(
            model_name="gpu",
            old_name="image_url",
            new_name="external_image",
        ),
        migrations.RenameField(
            model_name="internaldrive",
            old_name="image_url",
            new_name="external_image",
        ),
        migrations.RenameField(
            model_name="powersupply",
            old_name="image_url",
            new_name="external_image",
        ),
        migrations.RenameField(
            model_name="ram",
            old_name="image_url",
            new_name="external_image",
        ),
        migrations.AddField(
            model_name="case",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="case",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="cpu",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="gpu",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="internaldrive",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="internaldrive",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="powersupply",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="powersupply",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="ram",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="cpu",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="ram",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
