# Generated by Django 4.2.7 on 2023-12-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0106_remove_laptop_external_image_laptop_gpu_cores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="external_image",
            field=models.URLField(null=True),
        ),
    ]
