# Generated by Django 4.2.7 on 2023-12-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0107_laptop_external_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Field",
            new_name="PCField",
        ),
        migrations.AlterModelTable(
            name="pcfield",
            table="pc_field",
        ),
    ]
