# Generated by Django 4.2.7 on 2023-12-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0108_rename_field_pcfield_alter_pcfield_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaptopField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "laptop_field",
            },
        ),
    ]
