# Generated by Django 4.2.7 on 2023-12-31 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0109_laptopfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.laptopfield",
            ),
        ),
    ]
