# Generated by Django 4.2.7 on 2023-12-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0110_laptop_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="use",
        ),
    ]
