# Generated by Django 4.2.7 on 2023-12-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0111_remove_laptop_use"),
    ]

    operations = [
        migrations.RenameField(
            model_name="laptop",
            old_name="field",
            new_name="use",
        ),
    ]
