# Generated by Django 4.2.7 on 2023-12-31 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0112_rename_field_laptop_use"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaptopUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "laptop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.laptop",
                    ),
                ),
                (
                    "use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.laptopfield",
                    ),
                ),
            ],
            options={
                "db_table": "laptop_use",
            },
        ),
    ]
