# Generated by Django 4.2.7 on 2024-01-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0114_remove_laptop_use"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="url",
        ),
        migrations.RemoveField(
            model_name="cpu",
            name="url",
        ),
        migrations.RemoveField(
            model_name="gpu",
            name="url",
        ),
        migrations.RemoveField(
            model_name="internaldrive",
            name="url",
        ),
        migrations.RemoveField(
            model_name="motherboard",
            name="url",
        ),
        migrations.RemoveField(
            model_name="powersupply",
            name="url",
        ),
        migrations.RemoveField(
            model_name="ram",
            name="url",
        ),
    ]
