# Generated by Django 4.2.7 on 2024-01-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0115_remove_case_url_remove_cpu_url_remove_gpu_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cameras", models.CharField(max_length=255)),
                ("cpu", models.CharField(max_length=255)),
                ("core_count", models.PositiveIntegerField()),
                ("cpu_speed", models.FloatField()),
                ("storage", models.CharField(max_length=255)),
                ("ram", models.PositiveIntegerField()),
                ("screen_size", models.FloatField()),
                ("refresh_rate", models.PositiveIntegerField()),
                ("battery", models.PositiveIntegerField()),
                ("fast_charging", models.BooleanField(default=False)),
                ("main_camera", models.PositiveIntegerField()),
                ("front_camera", models.PositiveIntegerField()),
                ("cameras_num", models.PositiveIntegerField()),
                ("performance_class", models.CharField(max_length=255)),
                ("external_image", models.URLField(null=True)),
                ("image", models.ImageField(null=True, upload_to="images/phones/")),
            ],
            options={
                "db_table": "phone",
            },
        ),
        migrations.AlterField(
            model_name="case",
            name="image",
            field=models.ImageField(null=True, upload_to="images/cases/"),
        ),
        migrations.AlterField(
            model_name="cpu",
            name="image",
            field=models.ImageField(null=True, upload_to="images/cpus/"),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="image",
            field=models.ImageField(null=True, upload_to="images/gpus/"),
        ),
        migrations.AlterField(
            model_name="internaldrive",
            name="image",
            field=models.ImageField(null=True, upload_to="images/internal-drives/"),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="image",
            field=models.ImageField(null=True, upload_to="images/motherboards/"),
        ),
        migrations.AlterField(
            model_name="powersupply",
            name="image",
            field=models.ImageField(null=True, upload_to="images/power-supplies/"),
        ),
        migrations.AlterField(
            model_name="ram",
            name="image",
            field=models.ImageField(null=True, upload_to="images/rams/"),
        ),
    ]
