# Generated by Django 4.2.7 on 2024-01-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0118_mobileuse"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mobile",
            table="mobile",
        ),
    ]
