# Generated by Django 4.2.7 on 2024-01-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0119_alter_mobile_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobile",
            name="performance_class",
        ),
    ]
