# Generated by Django 4.2.7 on 2024-01-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0120_remove_mobile_performance_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptopfield",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="mobilefield",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="pcfield",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
