# Generated by Django 4.2.7 on 2024-01-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0121_alter_laptopfield_name_alter_mobilefield_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ram",
            name="timings",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
