# Generated by Django 4.2.7 on 2024-01-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0122_alter_ram_timings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpu",
            name="display_port",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="dvi",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="hdmi",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="vga",
            field=models.PositiveIntegerField(),
        ),
    ]
