# Generated by Django 4.2.7 on 2024-01-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0123_alter_gpu_display_port_alter_gpu_dvi_alter_gpu_hdmi_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="motherboard",
            name="display_port",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="dvi",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="vga",
            field=models.PositiveIntegerField(),
        ),
    ]
