# Generated by Django 4.2.7 on 2023-12-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardUser",
        ),
    ]
